export PATH=$PATH":./node_modules/.bin"
export PATH=$PATH":/usr/local/share/npm/bin"
export PATH=$PATH":~/node_modules/.bin"
export NODE_PATH=$NODE_PATH":/usr/local/lib/node"
export NODE_PATH=$NODE_PATH":/usr/local/lib/node_modules"